-- 补差价系统 DDL（可移植标准 SQL：H2 与 PostgreSQL 共用）
-- 使用 GENERATED BY DEFAULT AS IDENTITY（H2 2.x 与 PG 10+ 均支持），金额一律 BIGINT 分。

-- 后台管理员
CREATE TABLE IF NOT EXISTS admin_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(64),
    role          VARCHAR(32),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_user_username UNIQUE (username)
);

-- 补差价单（订单）
CREATE TABLE IF NOT EXISTS diff_order (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no             VARCHAR(64)  NOT NULL,
    short_code           VARCHAR(16)  NOT NULL,
    original_order_no    VARCHAR(64)  NOT NULL,
    original_amount_cent BIGINT,
    original_product     VARCHAR(255),
    product_name         VARCHAR(255) NOT NULL,
    quota_desc           VARCHAR(255),
    remark               VARCHAR(500),
    amount_cent          BIGINT       NOT NULL,
    status               VARCHAR(16)  NOT NULL,
    expire_at            TIMESTAMP    NOT NULL,
    created_by           VARCHAR(64)  NOT NULL,
    paid_at              TIMESTAMP,
    refund_status        VARCHAR(32),
    fulfill_status       VARCHAR(32),
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_diff_order_order_no   UNIQUE (order_no),
    CONSTRAINT uk_diff_order_short_code UNIQUE (short_code)
);

CREATE INDEX IF NOT EXISTS idx_diff_order_original_no ON diff_order (original_order_no);
CREATE INDEX IF NOT EXISTS idx_diff_order_status_expire ON diff_order (status, expire_at);
CREATE INDEX IF NOT EXISTS idx_diff_order_created_at ON diff_order (created_at);

-- 支付流水（一笔订单可多次发起支付）
CREATE TABLE IF NOT EXISTS payment_txn (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_no         VARCHAR(64) NOT NULL,
    order_id       BIGINT      NOT NULL,
    amount_cent    BIGINT      NOT NULL,
    status         VARCHAR(16) NOT NULL,
    channel        VARCHAR(16) NOT NULL,
    channel_txn_no VARCHAR(64),
    fail_reason    VARCHAR(255),
    success_at     TIMESTAMP,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payment_txn_txn_no         UNIQUE (txn_no),
    CONSTRAINT uk_payment_txn_channel_txn_no UNIQUE (channel_txn_no)
);

CREATE INDEX IF NOT EXISTS idx_payment_txn_order_id ON payment_txn (order_id);
